const { contextBridge, ipcRenderer } = require("electron");
window.addEventListener("DOMContentLoaded", () => {
  document.documentElement.dataset.platform = process.platform;
});
contextBridge.exposeInMainWorld(
  "eyeris",
  Object.fromEntries(
    [
      "init",
      "updateState",
      "checkForUpdates",
      "downloadUpdate",
      "installUpdate",
      "createProject",
      "openProject",
      "demo",
      "importFiles",
      "list",
      "behavior",
      "epochFields",
      "split",
      "linkBehavior",
      "diagnosticGroups",
      "average",
      "nextUnreviewed",
      "saveReviewPosition",
      "setAutoExclude",
      "trace",
      "decide",
      "undo",
      "exportData",
      "openRecent",
      "closeProject",
      "projectState",
      "addSubject",
      "addRecording",
      "importBids",
      "cancelImport",
      "startPipeline",
      "queuePipeline",
      "saveSettings",
      "recheckEyes",
      "eventPatterns",
      "setParallelJobs",
      "cancelPipeline",
      "pipelineLog",
      "showProjectFiles",
    ].map((method) => [
      method,
      (...args) => ipcRenderer.invoke(`review:${method}`, ...args),
    ]),
  ),
);
